import os
import json
import asyncio
import logging
import requests
import asyncpg
from typing import Dict, Any, List, Optional
from datetime import datetime
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Request, Header, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field


# --- CONFIGURATION ---
OPENROUTER_API_KEY = "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"
SITE_URL = "http://localhost:8000"
SITE_NAME = "MyFastAPIApp"
SCHEMA_PATH = r"e:\Banking_application\Banking_webApp\databaseService\banking_schema_attributes.md"

# Database Configuration
DATABASE_URL = "postgresql://bank_database_admin:admin123@localhost:5433/my_finance_db"

# Setup Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("FastAPIServer")

# --- DATA MODELS ---
class ChatRequest(BaseModel):
    user_id: str
    message: str
    token: Optional[str] = None

class FinancialAdviceRequest(BaseModel):
    user_id: str
    spending_data: Optional[Dict[str, float]] = None
    category: str = "grocery"
    target_reduction: Optional[float] = None
    token: Optional[str] = None

# --- APP LIFESPAN ---
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup: Connect to DB
    BLUE = "\033[94m"
    GREEN = "\033[92m"
    RED = "\033[91m"
    RESET = "\033[0m"
    
    print(f"{BLUE}--- STARTING FASTAPI SERVER ---{RESET}")
    print(f"{BLUE}Connecting to Database at {DATABASE_URL[:20]}...{RESET}")
    try:
        app.state.pool = await asyncpg.create_pool(DATABASE_URL)
        print(f"{GREEN}[SUCCESS] Database Connected Successfully!{RESET}")
    except Exception as e:
        print(f"{RED}[ERROR] Database Connection Failed: {e}{RESET}")
        app.state.pool = None
        
    yield
    
    # Shutdown: Close DB
    print(f"{BLUE}--- SHUTTING DOWN ---{RESET}")
    if app.state.pool:
        await app.state.pool.close()
        print(f"{BLUE}Database Connection Closed.{RESET}")

# --- APP SETUP ---
app = FastAPI(title="Banking AI Microservice", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- GLOBAL STATE ---
try:
    from ai_banking_agent import AIBankingAgent, UserContext, UserRole
    internal_agent = AIBankingAgent()
except ImportError:
    logger.error("Could not import AIBankingAgent. Ensure it is in the path.")
    internal_agent = None

# --- HELPER FUNCTIONS ---

import base64

def load_schema() -> str:
    """Load the banking schema markdown"""
    if os.path.exists(SCHEMA_PATH):
        with open(SCHEMA_PATH, "r", encoding="utf-8") as f:
            return f.read()
    return "Schema not found."

def extract_user_from_token(token: str) -> str:
    """
    Extracts the user ID (subject) from a JWT token without verifying signature.
    Useful for logging and context context before passing to secured backend.
    """
    try:
        # JWT is header.payload.signature
        parts = token.split(".")
        if len(parts) < 2:
            return "unknown_user"
        
        payload_b64 = parts[1]
        # Fix Base64 padding
        padding = '=' * (4 - len(payload_b64) % 4)
        payload_b64 += padding
        
        payload_bytes = base64.urlsafe_b64decode(payload_b64)
        payload_data = json.loads(payload_bytes)
        
        # Standard claims: 'sub' is usually user ID. 'preferred_username' is also common.
        return payload_data.get("sub") or payload_data.get("username") or "unknown_user"
    except Exception as e:
        logger.error(f"Error extracting user from token: {e}")
        return "unknown_user"


# Removed call_openrouter_brain - logic moved to internal_agent.process_user_intent

# Modified to return (results, error_message)
async def execute_raw_sql(sql_query: str, pool) -> (List[Dict], str):
    """
    Executes valid SQL generated by the Local Agent.
    Returns: (results_list, error_message)
    """
    if not pool:
        return [], "No connection pool available."

    # 1. Validation
    cleaned_sql = sql_query.strip()
    if not cleaned_sql.lower().startswith("select"):
        return [], "Blocked non-SELECT query for security."
    
    if ";" in cleaned_sql.replace(";", ""): 
        pass 
        
    print(f"   [DB] Executing SQL: {cleaned_sql}")
    
    try:
        async with pool.acquire() as connection:
            rows = await connection.fetch(cleaned_sql)
            return [dict(row) for row in rows], None # Success, No Error
    except Exception as e:
        print(f"[ERROR] [DB] Query Failed: {e}")
        return [], str(e) # Failure, Return Error

# --- ROUTES ---

@app.get("/health")
async def health_check():
    return {"status": "ok", "service": "fastapi-banking-agent"}

@app.post("/api/chat")
async def chat_endpoint(request: ChatRequest, authorization: Optional[str] = Header(None)):
    """
    Main Entry Point.
    1. Calls OpenRouter to classify.
    2. Routes to appropriate internal function.
    """
    token = request.token
    if not token and authorization:
        if authorization.startswith("Bearer "):
            token = authorization.split(" ")[1]
        else:
            token = authorization

    # Extract User ID from Token (Security Best Practice)
    user_id = request.user_id
    if token:
        extracted_user = extract_user_from_token(token)
        if extracted_user and extracted_user != "unknown_user":
            user_id = extracted_user

    # ANSI Color for Blue
    BLUE = "\033[94m"
    YELLOW = "\033[93m"
    RESET = "\033[0m"
    print(f"\n[INFO] [FASTAPI] Incoming Chat from {BLUE}{user_id}{RESET}: '{request.message}'")
    logger.info(f"Incoming Chat: {request.message}")
            
    
    # 1. Build User Context
    user_context = UserContext(
        user_id=user_id,
        role=UserRole.USER, # Default to user
        location="unknown",
        preferences={},
        transaction_history=[],
        token=token
    )
    
    # 2. Call Local Brain (Intent Classification & SQL Gen)
    if not internal_agent:
        return {"response": "AI Service Unavailable"}

    print("   [FASTAPI] Loading Schema & Calling Local Brain...")
    schema = load_schema()
    
    # Pass message, schema, AND user_id to LOCAL agent
    brain_response = await internal_agent.process_user_intent(request.message, schema, user_id)
    
    response_type = brain_response.get("type", "CHAT")
    
    print(f"[DECISION] [BRAIN DECISION] Type: {response_type}")
    print(f"[DEBUG] Raw Brain Response: {brain_response}")

    # 3. Execution Routing
    if response_type == "QUERY":
        sql_query = brain_response.get("sql")
        print(f"   [INTERNAL] Executing SQL: {sql_query}")
        
        # New Direct DB Execution (Raw SQL)
        results, error = await execute_raw_sql(sql_query, app.state.pool)
        
        # --- AUTO-CORRECTION LOOP (Multi-Turn) ---
        retry_count = 0
        max_retries = 2
        
        while error and retry_count < max_retries:
            retry_count += 1
            print(f"⚠️ [AUTO-CORRECT] Attempt {retry_count}/{max_retries}. Failed: {error}")
            
            # Attempt correction
            fixed_sql = await internal_agent.fix_sql_query(sql_query, error, schema)
            
            if fixed_sql:
                print(f"🔄 [AUTO-CORRECT] Retrying with: {fixed_sql}")
                # Execute the NEW query
                results, new_error = await execute_raw_sql(fixed_sql, app.state.pool)
                
                if new_error:
                    # If failed again, update error and query for next loop iteration
                    error = new_error
                    sql_query = fixed_sql # IMPORTANT: Feed the NEW broken query to the next fix
                    print(f"❌ [AUTO-CORRECT] Auto-Fix Failed: {new_error}")
                else:
                    # Success!
                    error = None
                    print(f"✅ [AUTO-CORRECT] Success on retry {retry_count}!")
            else:
                 print("Cannot generate fix.")
                 break # Cannot fix, exit loop
        
        if error:
             return {"response": f"I tried to process your request but encountered an internal database error even after {retry_count} retries: {error}"}
        # ----------------------------

        # Print Result in Yellow
        if results:
            print(f"{YELLOW}   [DB RESULT] {json.dumps(results, indent=2, default=str)}{RESET}")
        else:
            print(f"{YELLOW}   [DB RESULT] No records found.{RESET}")

        # Serialize results for response
        # In a real app, we might pass this back to LLM to summarize. 
        # For now, return the raw data nicely formatted or just the list.
        
        # Simple text formatter
        if results:
            if internal_agent:
                 print(f"   [INTERNAL] Summarizing {len(results)} rows with Local LLM...")
                 response_text = await internal_agent.summarize_query_results(results, request.message)
            else:
                 # Fallback if agent not loaded
                 response_text = f"Here is the data I found:\n\nFound {len(results)} records.\n"
                 for i, row in enumerate(results[:5]):
                     response_text += f"- {row}\n"
                 if len(results) > 5:
                     response_text += f"...and {len(results)-5} more."
        else:
             response_text = "I searched the database but found no matching records."
             
        print(f"[SUCCESS] [INTERNAL] Data Result: {len(results)} rows.")
        return {"response": response_text}
              
    else: 
        # CHAT MODE - Return OpenRouter's answer directly
        chat_response = brain_response.get("response") or "I couldn't generate a response."
        if not isinstance(chat_response, str):
            chat_response = str(chat_response)
            
        print(f"[SUCCESS] [BRAIN] Chat Response: {chat_response[:100]}...")
        return {"response": chat_response}

    return {"response": "I'm having trouble connecting to the Banking Brain right now."}

@app.post("/api/user/financial-advice")
async def manual_advice_endpoint(request: FinancialAdviceRequest, authorization: Optional[str] = Header(None)):
    """Direct advice endpoint (Legacy/Direct Access)"""
    # ANSI Color for Blue
    BLUE = "\033[94m"
    RESET = "\033[0m"
    
    try:
        # Extract Token
        token = request.token
        if not token and authorization:
            if authorization.startswith("Bearer "):
                token = authorization.split(" ")[1]
            else:
                token = authorization
        
        # Extract User ID from Token
        user_id = request.user_id # Fallback
        if token:
            extracted_user = extract_user_from_token(token)
            if extracted_user and extracted_user != "unknown_user":
                user_id = extracted_user
        
        print(f"\n[INFO] [FASTAPI] Financial Advice Request for {BLUE}{user_id}{RESET}")

        
        real_transactions = []
        if token:
             headers = {"Authorization": f"Bearer {token}"}
             try:
                 print("   [INTERNAL] Fetching transactions from Spring API...")
                 # Verify port 8082 or 8080. Previous code used 8082.
                 response = requests.get(f"http://localhost:8082/api/transactions/current-user?limit=100", headers=headers, timeout=5)
                 if response.status_code == 200:
                     real_transactions = response.json()
                     print(f"   [INTERNAL] Got {len(real_transactions)} transactions.")
             except Exception as e:
                 print(f"   [INTERNAL] Transaction fetch failed: {e}")
        
        # Calculate Spending
        spending_data = {}
        if real_transactions:
            now = datetime.now()
            # Simple weekly aggregation
            # ... (Logic copied from Flask)
            pass # Simplified for resilience, relying on Agent to analyze list.
        else:
             spending_data = request.spending_data or {
                'week1': 120.50, 'week2': 145.30, 'week3': 135.80, 'week4': 160.20
            }

        user_context = UserContext(
            user_id=user_id,
            role=UserRole.USER,
            location="toronto", # Default
            preferences={},
            transaction_history=real_transactions,
            token=token
        )
        
        if internal_agent:
            print("   [INTERNAL] Calling Agent for Advice...")
            
            advice = await internal_agent.provide_financial_advice(
                user_context=user_context,
                spending_data=spending_data,
                category=request.category,
                target_reduction=request.target_reduction
            )
            
            return {
                "success": True,
                "advice": {
                    "analysis_summary": advice.analysis_summary,
                    "weekly_spending": advice.weekly_spending,
                    "recommended_reduction": advice.recommended_reduction,
                    "savings_suggestions": advice.savings_suggestions,
                    "grocery_deals": advice.grocery_deals,
                    "action_plan": advice.action_plan
                },
                "real_data": {
                    "transaction_count": len(real_transactions),
                    "data_source": "database" if real_transactions else "mock",
                    "spending_breakdown": spending_data
                },
                "timestamp": datetime.now().isoformat()
            }
            
    except Exception as e:
        logger.error(f"Advice Error: {e}")
        return {"success": False, "error": str(e)}

    return {"status": "error", "message": "Agent not initialized"}

if __name__ == "__main__":
    import uvicorn
    # Use lifespan logic
    uvicorn.run("fastapi_server:app", host="0.0.0.0", port=5000, reload=True)
